name: Deploy to UBA-DEV

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: UBA-DEV

    steps:
      - name: Deploy via SSH and Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.TARGET_DIR }}

            # Write .env file
            echo '${{ secrets.DEV_ENV }}' > .env

            # Login to Docker Hub (optional if public image)
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Pull latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ubi-strapi-provider-mw:latest

            # Stop and remove old container if it exists
            docker rm -f ubi-strapi-provider-mw-onest || true

            # Start new container
            docker run -d --name ubi-strapi-provider-mw-onest \
              --env-file .env \
              -p 1338:1338 \
              ${{ secrets.DOCKERHUB_USERNAME }}/ubi-strapi-provider-mw:latest

            # Wait for it to boot
            sleep 10

            # Logs
            docker logs ubi-strapi-provider-mw-onest
