name: Deploy to UBA-PILOT

on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Docker image tag to deploy'
        required: true
        default: 'v0.0.0'
      BRANCH:
        description: 'Git branch to deploy'
        required: true
        default: 'main'
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  Deploy_on_UBA_PILOT:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: UBA-DEPWD-PILOT

    steps:
      - name: Deploy Strapi MW via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME_PILOT }}
          username: ${{ secrets.USERNAME_PILOT }}
          key: ${{ secrets.EC2_SSH_KEY_PILOT }}
          port: ${{ secrets.PORT_PILOT }}
          script: |
            # ----- Set environment variables -----
            export BASE_DIR="${{ secrets.TARGET_DIR_PILOT }}"
            export REPO_NAME="ubi-strapi-provider-mw"
            export REPO_URL="https://github.com/PSMRI/ubi-strapi-provider-mw.git"
            export BRANCH="${{ github.event.inputs.BRANCH || 'main' }}"
            export TAG="${{ github.event.inputs.TAG || github.ref_name || 'latest' }}"
            export CONTAINER_NAME="ubi-strapi-provider-mw-onest"

            cd "$BASE_DIR" || exit 1

            # ----- Prepare .env -----
            if [ -f .env ]; then rm .env; fi
            echo '${{ secrets.DEV_ENV_PILOT }}' > .env

            # ----- Run deploy script -----
            bash deploy.sh

      - name: Notify on Slack channel
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
